### ISSUE TITLE
Allow user to create multiple Scannit instances

### ISSUE THREAD

**Issue by vpartington** [hierynomus/scannit#5]
Currently only one Scannit can be booted in one JVM. I can force the single instance to reinitialize itself but I'd rather just have multiple instances if I want to scan different things in different parts of my code.

**Comment by hierynomus** [comment]
This is possible. Instead of `Scannit.boot(config)` and `Scannit.getInstance()` you can also do `new Scannit(config)`, which does not set the static instance.
